### ISSUE TITLE
阿杰，阿杰，能留个联系方式吗

### ISSUE THREAD

**Issue by W-Hui-z** [YIRUIJIE/StudentMangerSystem#1]
没啥安卓基础，但毕设是这玩意，你的版本是哪个版本啊，好搞人啊这个版本

**Comment by W-Hui-z** [comment]
> 没啥安卓基础，但毕设是这玩意，你的版本是哪个版本啊，好搞人啊这个版本

**Comment by YIRUIJIE** [comment]
当时写毕业设计的时候随便创建的版本，记不清楚了，应该是一个挺老的版本，你可以下载下来尝试一下！
当时用的环境是：Eclipse+ADT+Android SDK 搭建安卓开发环境
你可以使用Android studio&nbsp;尝试一下！






瑞杰
yiruijie@foxmail.com



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YIRUIJIE/StudentMangerSystem"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月9日(星期一) 上午9:13
收件人:&nbsp;"YIRUIJIE/StudentMangerSystem"<StudentMangerSystem@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[YIRUIJIE/StudentMangerSystem] 阿杰，阿杰，能留个联系方式吗 (#1)





 
没啥安卓基础，但毕设是这玩意，你的版本是哪个版本啊，好搞人啊这个版本

**Comment by W-Hui-z** [comment]
感谢指路， 我去试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YIRUIJIE/StudentMangerSystem"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月9日(星期一) 上午9:24
收件人:&nbsp;"YIRUIJIE/StudentMangerSystem"<StudentMangerSystem@noreply.github.com&gt;;
抄送:&nbsp;"朱先锋"<feng58@vip.qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [YIRUIJIE/StudentMangerSystem] 阿杰，阿杰，能留个联系方式吗 (#1)





 当时写毕业设计的时候随便创建的版本，记不清楚了，应该是一个挺老的版本，你可以下载下来尝试一下！ 
 当时用的环境是：Eclipse+ADT+Android SDK 搭建安卓开发环境 
 你可以使用Android studio&amp;nbsp;尝试一下！ 
 
 
 
 
 
 
 瑞杰 
 yiruijie@foxmail.com 
 
 
 
 &amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "YIRUIJIE/StudentMangerSystem"                                                                                    <notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年11月9日(星期一) 上午9:13 
 收件人:&amp;nbsp;"YIRUIJIE/StudentMangerSystem"<StudentMangerSystem@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"Subscribed"<subscribed@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;[YIRUIJIE/StudentMangerSystem] 阿杰，阿杰，能留个联系方式吗 (#1) 
 
 
 
 
 
   
 没啥安卓基础，但毕设是这玩意，你的版本是哪个版本啊，好搞人啊这个版本
